### ISSUE TITLE
Editing a review with a partial star rounds the star value up

### ISSUE THREAD

**Issue by Tak** [bookwyrm-social/bookwyrm#2213]
Editing a review with a partial star rounds the star value up

1. Post a review with a partial star
2. Click `Edit` in the post's context menu

**Expected behavior**
The star value is unchanged

**Actual behavior**
The star value is rounded up

**Instance**
reading.taks.garden

**Additional context**
Probably shares a similar root cause as https://github.com/bookwyrm-social/bookwyrm/issues/1505

**Comment by hughrun** [comment]
I can't replicate this, but I can see some behaviour that is intended but I find confusing. In the default css we have this:

```css
/* All stars are visually filled by default. */
.form-rate-stars .icon::before {
  content: "\e9d9";
  /* icon-star-full */ }
```

This over-rides the `icon-star-empty` class on child `<label>` elements.

In the `snippets/form_rate_stars.html` template we also seem to be missing logic for half-stars on the relevant `label` element, though it's possible I'm just not seeing it, there's a lot going on there.

@mouse-reeve not sure what the intention is in this form? Should it show five stars when editing, regardless of the current rating?
