### ISSUE TITLE
Add `docker-compose.yml.example` to the repository to prevent user configurations from being overwritten

### ISSUE THREAD

**Issue by Guanchishan** [bookwyrm-social/bookwyrm#3447]
**Is your feature request related to a problem? Please describe.**  
Currently, every time the `docker-compose.yml` file is pulled from the Git repository, it overwrites any local modifications. This is frustrating, as the `docker-compose.yml` often contains user-specific configurations that are essential for adapting the deployment to the user’s environment. While the changes can be manually handled by staging or skipping updates, this process is cumbersome and prone to errors.

**Describe the solution you'd like**  
A more elegant solution would be to add a `docker-compose.yml.example` to the Git repository and track that file instead. In the installation documentation, users should be instructed to create their own configuration by copying from this example file:  
```bash
cp docker-compose.yml.example docker-compose.yml
```
This approach would help users preserve their local environment-specific configuration changes without the risk of them being overwritten during repository updates.

**Describe alternatives you've considered**  
An alternative is to use git to stash changes to `docker-compose.yml` before pulling updates, then reapply those changes afterward. However, this solution is not as user-friendly and adds an extra layer of manual work each time the repository is updated.

**Additional context**  
Including this change in the [documentation](https://docs.joinbookwyrm.com/install-prod.html) would enhance the usability of the project and reduce the chances of users accidentally overwriting their deployment configurations.

**Comment by hughrun** [comment]
@Guanchishan can you give an example of the sort of thing admins would want to change in the `docker-compose` file? It's quite typical for projects like BookWyrm to use a standard `docker-compose` and helps maintain consistent environments. Generally customisations should be environment variables so if there is something you think should be customisable it may be better to adjust the docker-compose file itself to pull in an `ENV`.

**Comment by Guanchishan** [comment]
Reply to @hughrun:

>  It's quite typical for projects like BookWyrm to use a standard `docker-compose` and helps maintain consistent environments. 

Thank you for pointing out that keeping the Docker configuration consistent helps ensure a stable deployment. However, some users—including myself—may require more extensive customizations than environment variables alone can provide.

For example, I run my Redis and PostgreSQL services on separate hosts, so I need to comment out the corresponding service definitions in the docker-compose.yml. I’ve also set the network mode to host and provided custom DNS settings for the web service.

I’ll share my actual `docker-compose.yml` shortly to illustrate these customizations in more detail.

```YAML
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "150m"
    max-file: "2"

services:
  nginx:
    image: nginx:1.25.2
    logging: *default-logging
    restart: unless-stopped
    network_mode: "host"  # The same network mode as the `web` container, directly connecting to the host network.
    entrypoint: /bin/sh -c "chown -R nginx:nginx /app/static /app/images && nginx -g 'daemon off;'"
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./images:/app/images
  web:
    build: .
    env_file: .env
    network_mode: "host" # Connect to the host network.
    command: gunicorn bookwyrm.wsgi:application --threads=8 --bind 0.0.0.0:8000
    logging: *default-logging
    volumes:
      - .:/app
      - ./static:/app/static
      - ./images:/app/images
      - ./exports:/app/exports
    depends_on:
      - celery_worker
    dns:
      - 1.1.1.1
      - 1.0.0.1
  celery_worker:
    env_file: .env
    build: .
    network_mode: "host"  # The same network mode as the `web` container, directly connecting to the host network.
    command: celery -A celerywyrm worker -l info -Q high_priority,medium_priority,low_priority,streams,images,suggested_users,email,connectors,lists,inbox,imports,import_triggered,broadcast,misc
    logging: *default-logging
    volumes:
      - .:/app
      - ./static:/app/static
      - ./images:/app/images
    restart: on-failure
  celery_beat:
    env_file: .env
    build: .
    network_mode: "host"  # 与 web 容器相同的网络模式，直接连接宿主机网络
    command: celery -A celerywyrm beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    logging: *default-logging
    volumes:
      - .:/app
      - ./static:/app/static
      - ./images:/app/images
    depends_on:
      - celery_worker
    restart: on-failure

```

Changes I made:

1. Network mode
   - I replaced the project-internal network (`networks: - main`) with `network_mode: "host"` on **all core services** (nginx, web, celery_worker, celery_beat). This lets each container share the host’s network stack directly, so I don’t need to map ports explicitly.  

2. External services
   - I removed the built-in `db`, `redis_activity`, and `redis_broker` service definitions, because I run Redis and PostgreSQL on separate hosts. This avoids spinning up additional containers I don’t use.  

3. Port mappings
   - With host networking enabled, I **deleted** the `ports:` mappings under both `nginx` and `web`, since the containers now listen directly on the host interfaces.  

6. DNS settings
   - I added a custom `dns:` section to the `web` service (1.1.1.1, 1.0.0.1) so that its DNS resolution goes through Cloudflare.  

7. Custom Nginx entrypoint
   - I overrode `nginx`’s entrypoint to `chown -R nginx:nginx /app/static /app/images && nginx -g 'daemon off;'`, ensuring proper file ownership before starting.  

8. Removed auxiliary services
   - I **omitted** the `certbot`, `flower`, and `dev-tools` services. In particular, I commented out `certbot` because I already have an external HTTPS solution and don’t need the built-in certificate provisioning.  

As well as some other minor modifications.
